TRAIN:
  DATASET: 'TRACINGSEG'
  BATCH_SIZE: 1
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 0
DATA:
  CROP_SIZE: 64
DATA_LOADER:
  PIN_MEMORY: false
  NUM_WORKERS: 4
NVT:
  NUM_MULTI_PATCHES: 4
  PATCH_SELECTION_POLICY: true
  SELECTION_LB: 0
  RANDOM_CROP_THRESHOLD: 0
  BINARY_SEG: true
MODEL:
  NUM_CLASSES: 1
  LOSS_FUNC: 'DiceLoss'
  N_BASE_FILTERS: 16
  ENCO_DEPTH: 5
  NUM_PRED_LEVELS: 3
  DROPOUT_RATE: 0.50
  MODEL_NAME: 'Unet3D'  # 'Unet3D', 'NestedUnet3D', 'Unet3DCBAM', 'DAUnet3D'
  SETTINGS:
    NestedUnet3D:
        DEEP_SUPERVISION: true
        N_HOP_DENSE_SKIP_CONNECTION: 2
        MODULATION_TYPE: concatenation
    DAUnet3D:
      GAM:
        BLOCKS:
          - -1
      LAM:
        BLOCKS:
          - 3
          - 4
        RESIDUAL_RELATIVE: before
        INPUT_REDUCTION_RATIO: 2
        MIDDLE_REDUCTION_RATIO: 4
        INTERNAL_MODULATION_TYPE: additive
        CROSS_MODAL_MODULATION_TYPE: additive
        REF_MODULATION_TYPE: additive
        RESIDUAL: true
        CHANNEL: true
        SPATIAL: true
        KERNEL_SIZE: 5
SOLVER:
  OPTIMIZING_METHOD: 'adam'
  BASE_LR: 1e-3
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
  MAX_EPOCH: 100
  NESTEROV: false
  SCHEDULER_MODE: false
LOG_PERIOD: 1
USE_GPU: true
GPU_ID: 0
AMP: false
