MODEL:
  MODEL_NAME: Unet3D
  LOSSES:
    - name: 'DiceLoss'
      weight: 1.0
      with_logits: true
#    - name: 'FocalLoss'
#      weight: 0.1
#      with_logits: true
#    - name: 'MSELoss'
#      weight: 0.1
#      with_logits: true
PROJECT:
  PA_INDICES: true
TRAIN:
  DATASET: SRIBIL
  CHECKPOINT_PERIOD: 1
WMH:
  HFB_MASKING_MODE: pipeline
  BINARIZE_THRESHOLD: 0.5
  HFB_GT: true
SOLVER:
  MAX_EPOCH: 200
  BASE_LR: 0.001

USE_GPU: true
GPU_ID: 0
AMP: false
DP: false
DDP: false