TRAIN:
  BATCH_SIZE: 1
DATA:
  CROP_SIZE: 64
DATA_LOADER:
  PIN_MEMORY: false
  NUM_WORKERS: 8
LOG_PERIOD: 1
NVT:
  NUM_MULTI_PATCHES: 2  # 32/8
  PATCH_SELECTION_POLICY: true
  SELECTION_LB: 128000  # CAPTURE: 2K/4K | TRAP: 128K
  RANDOM_CROP_NUM_ATTEMPS: 500
  RANDOM_CROP_THRESHOLD: 0
MODEL:
  LOSS_FUNC: 'DiceLoss'  # 'CrossEntropyLoss'  # 'DiceLoss'
  LOSS_AUG_WHL: true
  WHL_NUM_DEPTH_SHEETS: 16  # (2, 4, 8, 16)
  WHL_SEG_THR: 0.5  # (0.12, 0.25, 0.5)
SOLVER:
#  OPTIMIZING_METHOD: 'sgd'
  SCHEDULER_MODE: true