BN:
  WEIGHT_DECAY: 0.0
DATA:
  CROP_SCALE:
  - 0.8
  - 1.0
  CROP_SIZE: 160
  ENFORCE_DIAG: true
  ENFORCE_NIB_CANONICAL: false
  EXP:
    BODY_CRO: 0
    BODY_FLI: 0
    HEAD_ORI: 0
    HEAD_RES: 0
    INTENSITY: True
    INTENSITY_SEL: 9
  MAX_SIDE_SIZE: 192
  MEAN:
  - 0.18278566002845764
  - 0.1672040820121765
  MIN_SIDE: false
  PADDING_MODE: mean
  STD:
  - 0.018310515210032463
  - 0.017989424988627434
  UNI_SCALE: true
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: true
GPU_ID: 0
HPO:
  EVAL_METRIC: jaccard_ind
  MAX_EPOCH: 200
  MODE: BOAX
  RANGE_LEN: 0
  RANGE_START: 0
  TOTAL_TRIALS: 100
LOG_PERIOD: 2
MODEL:
  ARCH: unet3d
  DROPOUT_RATE: 0.3
  ENCO_DEPTH: 5
  FC_INIT_STD: 0.01
  IGNORE_INDEX: 255
  INPUT_CHANNELS: 2
  LOSS_AUG_WHL: false
  LOSS_FUNC: DiceLoss
  MODEL_NAME: Unet3D
  NUM_CLASSES: 1
  NUM_PRED_LEVELS: 3
  N_BASE_FILTERS: 16
  WHL_NUM_DEPTH_SHEETS: 8
  WHL_SEG_THR: 0.25
NUM_GPUS: 1
PROJECT:
  DATASET_DIR: /gpfs/fs0/scratch/m/mgoubran/mbiparva/wmh_pytorch/dataset
  EXPERIMENT_DIR: /gpfs/fs0/scratch/m/mgoubran/mbiparva/wmh_pytorch/experiments
  METERS:
  - loss
  - dice_coeff
  - jaccard_ind
  - hausdorff_dist
  MODELS_DIR: /gpfs/fs0/scratch/m/mgoubran/mbiparva/wmh_pytorch/lib/models
  ROOT_DIR: /gpfs/fs0/scratch/m/mgoubran/mbiparva/wmh_pytorch
  TSR: 0.0
  TVSR: 0.8
RNG_SEED: 110
SOLVER:
  BASE_LR: 0.001
  DAMPENING: 0
  MAX_EPOCH: 100
  MOMENTUM: 0.8
  NESTEROV: false
  OPTIMIZING_METHOD: adagrad
  SCHEDULER_MODE: false
  SCHEDULER_TYPE: step
  WEIGHT_DECAY: 1.0e-05
TEST:
  BATCH_MODE: false
  BATCH_SIZE: 1
  BINARIZE_THRESHOLD: 0.55
  CHECKPOINT_FILE_PATH: ''
  DATASET: PPMITest
  DATA_PATH: ''
  ENABLE: false
  IN_MOD:
  - - t1
    - T1_nu.img
  - - fl
    - T1acq_nu_FL.img
  - - annot
    - T1acq_nu_HfBd.img
TRAIN:
  AUTO_RESUME: true
  BATCH_SIZE: 1
  CHECKPOINT_FILE_PATH: ''
  CHECKPOINT_PERIOD: 20
  DATASET: SRIBIL
  ENABLE: true
  EVAL_PERIOD: 1
  HPO: false
  IN_MOD:
  - - t1
    - T1_nu.nii.gz
  - - fl
    - T1acq_nu_FL.nii.gz
  - - annot
    - wmh_seg.nii.gz
  SHUFFLE: true
VALID:
  BATCH_SIZE: 1
  ENABLE: true
WMH:
  BINARIZE_THRESHOLD: 0.5
  ENABLE: true
  FILL: 0
  HFB_CHECKPOINT: /gpfs/fs0/scratch/m/mgoubran/mbiparva/wmh_pytorch/experiments/SRIBILhfb/20200612_134356_471570/checkpoints/checkpoint_epoch_00060.pyth
  HFB_GT: false
  MAX_SIDE_SIZE: 160
  PADDING_MODE: mean
