WMH:
  BINARIZE_THRESHOLD: 0.5
  PADDING_MODE: mean
  FILL: 0
  HFB_GT: true
  CROPPING: true
  RESIZING_PADDING: false
  MAX_SIDE_SIZE: 160
TRAIN:
  DATASET: 'SRIBIL'
TEST:
  ENABLE: true
  DATASET: 'SRIBILTest'
  BATCH_MODE: true
  BINARIZE_THRESHOLD: 0.50
  CHECKPOINT_FILE_PATH: ''
  DATA_PATH: ''
  ROBUST_EXP: true
  EVAL_METRICS:
    - 'dice_coefficient'
    - 'jaccard_index'
    - 'hausdorff_distance'
    - 'rvd'
  ROBUST_EXP_LIST:
    - - t_name: 'biasfield'
        t_params:
          coefficients:
            - 0.5
            - 1.0
            - 1.5
            - 0.5
            - 1.0
            - 1.5
          order:
            - 3
            - 3
            - 3
            - 2
            - 2
            - 2
    - - t_name: 'blur'
        t_params:
          std:
            - 0.1
            - 0.2
            - 0.3
    - - t_name: 'contrastchannel'
        t_params:
          value:
            - - -0.4
              - -0.3
            - - -0.1
              - -0.0
            - - +0.1
              - +0.2
            - - +0.4
              - +0.45
    - - t_name: 'noisechannel'
        t_params:
          sigma:
            - - 0.1
              - 0.2
            - - 0.5
              - 0.6
            - - 0.90
              - 0.95
          noise_type:
            - 'gaussian'
            - 'gaussian'
            - 'gaussian'
    - - t_name: 'noise'
        t_params:
          sigma:
            - 0.1
            - 0.5
            - 0.9
          noise_type:
            - 'gaussian'
            - 'gaussian'
            - 'gaussian'
    - - t_name: 'contrast'
        t_params:
          value:
            - -0.4
            - -0.1
            - +0.1
            - +0.4
    - - t_name: 'noise'
        t_params:
          sigma:
            - 0.1
            - 0.5
            - 0.9
          noise_type:
            - 'gaussian'
            - 'gaussian'
            - 'gaussian'
      - t_name: 'contrast'
        t_params:
          value:
            - -0.4
            - +0.1
            - +0.4
    - - t_name: 'motion'
        t_params:
          time:
            - 0.5
            - 0.9
