TRAIN:
  DATASET: 'HPSubfield'
  BATCH_SIZE: 1
DATA_LOADER:
  PIN_MEMORY: false
  NUM_WORKERS: 4
LOG_PERIOD: 1
#HPSF:
MODEL:
  LOSS_FUNC: 'DiceLoss'  # 'CrossEntropyLoss', 'DiceLoss', 'WeightedHausdorffLoss', 'FocalLoss', 'LovaszLoss'
  N_BASE_FILTERS: 16
  ENCO_DEPTH: 5  # 5
  NUM_PRED_LEVELS: 3  # 3 - max is ENCO_DEPTH - 1
  DROPOUT_RATE: 0.30
  MODEL_NAME: 'Unet3D' # 'Unet3D', 'NestedUnet3D'
  NUM_CLASSES: 3
SOLVER:
#  OPTIMIZING_METHOD: 'sgd'
#  BASE_LR: 1e-2
#  MOMENTUM: 0.9
#  WEIGHT_DECAY: 1e-5
#  MAX_EPOCH: 100
#  NESTEROV: false
  SCHEDULER_MODE: false

USE_GPU: true
GPU_ID: 0
AMP: false
DP: false
DDP: false
