TRAIN:
  BATCH_SIZE: 1
  CHECKPOINT_PERIOD: 0
  DATASET: 'TRAP'
DATA:
  CROP_SIZE: 64
DATA_LOADER:
  PIN_MEMORY: false
  NUM_WORKERS: 4
LOG_PERIOD: 1
NVT:
  NUM_MULTI_PATCHES: 16
  PATCH_SELECTION_POLICY: true
  SELECTION_LB: 16000
  RANDOM_CROP_THRESHOLD: 0
MODEL:
  N_BASE_FILTERS: 16
  ENCO_DEPTH: 5
  NUM_PRED_LEVELS: 3
  DROPOUT_RATE: 0.30
  MODEL_NAME: Unet3D
  LOSSES:
    - name: 'DiceLoss'
      weight: 1.0
      with_logits: true
#    - name: 'FocalLoss'
#      weight: 0.1
#      with_logits: true
#    - name: 'MSELoss'
#      weight: 0.1
#      with_logits: true
SOLVER:
  MAX_EPOCH: 200
  OPTIMIZING_METHOD: adam
  BASE_LR: 1e-3
  MOMENTUM: 0.8
  WEIGHT_DECAY: 1e-5
  SCHEDULER_MODE: false
USE_GPU: true
GPU_ID: 0
AMP: false
