TRAIN:
  BATCH_SIZE: 1
DATA:
  CROP_SIZE: 64
DATA_LOADER:
  PIN_MEMORY: false
  NUM_WORKERS: 4
LOG_PERIOD: 1
NVT:
  NUM_MULTI_PATCHES: 16
  PATCH_SELECTION_POLICY: true
  SELECTION_LB: 16000
  RANDOM_CROP_NUM_ATTEMPS: 500
  RANDOM_CROP_THRESHOLD: 0
MODEL:
  LOSS_FUNC: DiceLoss
  N_BASE_FILTERS: 16
  ENCO_DEPTH: 5
  NUM_PRED_LEVELS: 3
  DROPOUT_RATE: 0.30
  MODEL_NAME: Unet3D
SOLVER:
  MAX_EPOCH: 200
  OPTIMIZING_METHOD: adam
  BASE_LR: 1e-3
  MOMENTUM: 0.8
  WEIGHT_DECAY: 1e-5
  NESTEROV: false
  SCHEDULER_MODE: false
USE_GPU: true
GPU_ID: 0
AMP: false
DP: false
DDP: false
