TRAIN:
  BATCH_SIZE: 1
DATA:
  CROP_SIZE: 64
DATA_LOADER:
  PIN_MEMORY: false
  NUM_WORKERS: 4
LOG_PERIOD: 1
NVT:
  NUM_MULTI_PATCHES: 8
  PATCH_SELECTION_POLICY: true
  SELECTION_LB: 100
  RANDOM_CROP_NUM_ATTEMPS: 500
  RANDOM_CROP_THRESHOLD: 0