TRAIN:
  BATCH_SIZE: 1
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 0
DATA:
  CROP_SIZE: 64
DATA_LOADER:
  PIN_MEMORY: false
  NUM_WORKERS: 4
NVT:
  NUM_MULTI_PATCHES: 4
  PATCH_SELECTION_POLICY: true
  SELECTION_LB: 0
  RANDOM_CROP_THRESHOLD: 0
MODEL:
  LOSS_FUNC: 'DiceLoss'
  LOSS_AUG_WHL: false
  N_BASE_FILTERS: 16
  ENCO_DEPTH: 5
  NUM_PRED_LEVELS: 3
  DROPOUT_RATE: 0.50
  MODEL_NAME: 'Unet3D'
SOLVER:
  OPTIMIZING_METHOD: 'adam'
  BASE_LR: 1e-3
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
  MAX_EPOCH: 100
  NESTEROV: false
  SCHEDULER_MODE: false
LOG_PERIOD: 1
USE_GPU: true
GPU_ID: 0
AMP: false
